package com.try_catch_finally;

import java.util.concurrent.ConcurrentHashMap;

public class ExceptionHandlingExamples {
/*
 * by shubham ashtaputre
 */
	public static void main(String[] args) {
		/*
		try {
			int i = 10;
			int j=0;
			int c = 10/0;
			System.out.println("Result: "+c);
		} finally {
			System.out.println("Finally block executed");
		}
		*/
		
		/*
		try {
			i = 10;
			j=0;
		} finally {
			try {
				c = i/j;
				if(c!=0) {
					System.out.println("Inside try block");
				}
			}catch (Exception e) {
				System.out.println("Inside Exception: "+e);
			}
			
		}
		*/
		
	}

}
